/*
  # Initial Database Schema for Taruna Karya Kampung Ciperang

  1. New Tables
    - `artikel` - Articles/news management
      - `id` (bigint, primary key, auto increment)
      - `judul` (text, article title)
      - `isi` (text, article content)
      - `gambar` (text, image URL)
      - `tanggal` (date, publication date)
      - `created_at` (timestamp, auto-generated)

    - `anggota` - Members management
      - `id` (bigint, primary key, auto increment)
      - `nama` (text, member name)
      - `jabatan` (text, member position/role)
      - `foto` (text, photo URL)
      - `kontak` (text, contact information)
      - `created_at` (timestamp, auto-generated)

    - `galeri` - Gallery/photo management
      - `id` (bigint, primary key, auto increment)
      - `url_foto` (text, photo URL)
      - `keterangan` (text, photo description)
      - `created_at` (timestamp, auto-generated)

  2. Security
    - Enable RLS on all tables
    - Add policies for authenticated users to read data
    - Add policies for authenticated users to manage data (insert, update, delete)
    - Add policies for anonymous users to read data

  3. Sample Data
    - Insert sample articles, members, and gallery items for demonstration
*/

-- Create artikel table
CREATE TABLE IF NOT EXISTS artikel (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  judul text NOT NULL,
  isi text NOT NULL,
  gambar_url text,  -- URL langsung dari internet
  tanggal date NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamptz DEFAULT now()
);

-- Create anggota table
CREATE TABLE IF NOT EXISTS anggota (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama text NOT NULL,
  jabatan text NOT NULL,
  foto text,
  kontak text,
  created_at timestamptz DEFAULT now()
);

-- Create galeri table
CREATE TABLE IF NOT EXISTS galeri (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url_foto text NOT NULL,
  keterangan text,
  created_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE artikel ENABLE ROW LEVEL SECURITY;
ALTER TABLE anggota ENABLE ROW LEVEL SECURITY;
ALTER TABLE galeri ENABLE ROW LEVEL SECURITY;

-- Policies for artikel table
CREATE POLICY "Anyone can read articles"
  ON artikel
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert articles"
  ON artikel
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update articles"
  ON artikel
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Authenticated users can delete articles"
  ON artikel
  FOR DELETE
  TO authenticated
  USING (true);

-- Policies for anggota table
CREATE POLICY "Anyone can read members"
  ON anggota
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert members"
  ON anggota
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update members"
  ON anggota
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Authenticated users can delete members"
  ON anggota
  FOR DELETE
  TO authenticated
  USING (true);

-- Policies for galeri table
CREATE POLICY "Anyone can read gallery"
  ON galeri
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert gallery items"
  ON galeri
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update gallery items"
  ON galeri
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Authenticated users can delete gallery items"
  ON galeri
  FOR DELETE
  TO authenticated
  USING (true);

-- Insert sample data for artikel
INSERT INTO artikel (judul, isi, gambar, tanggal) VALUES
(
  'Kegiatan Kerja Bakti Rutin Minggu Lalu',
  'Pada hari Minggu yang lalu, warga Kampung Ciperang kembali mengadakan kegiatan kerja bakti rutin yang diikuti oleh seluruh anggota Taruna Karya. Kegiatan ini meliputi pembersihan jalan utama, penataan taman kampung, dan perbaikan fasilitas umum. Antusiasme warga sangat tinggi, terlihat dari partisipasi aktif dari berbagai kalangan usia. Kegiatan dimulai pukul 07.00 WIB dan berakhir pada pukul 11.00 WIB. Hasil yang dicapai sangat memuaskan, kampung terlihat lebih bersih dan asri.',
  'https://images.pexels.com/photos/6646918/pexels-photo-6646918.jpeg?auto=compress&cs=tinysrgb&w=600',
  '2024-01-15'
),
(
  'Pengajian Rutin Malam Jumat',
  'Setiap malam Jumat, masjid kampung selalu ramai dengan kegiatan pengajian yang diselenggarakan oleh Taruna Karya Kampung Ciperang. Kegiatan spiritual ini diikuti oleh warga dari berbagai RT dan RW di sekitar kampung. Tema pengajian kali ini adalah tentang pentingnya menjaga lingkungan dalam perspektif Islam. Ustadz Ahmad menyampaikan materi dengan sangat menarik dan mudah dipahami. Para jamaah juga antusias bertanya dan berdiskusi setelah ceramah selesai.',
  'https://images.pexels.com/photos/8088495/pexels-photo-8088495.jpeg?auto=compress&cs=tinysrgb&w=600',
  '2024-01-12'
),
(
  'Persiapan Perayaan HUT RI ke-79',
  'Taruna Karya Kampung Ciperang telah memulai persiapan untuk menyambut HUT RI ke-79. Berbagai lomba dan kegiatan menarik telah disiapkan, mulai dari lomba tradisional hingga modern. Panitia telah dibentuk dan pembagian tugas sudah dilakukan. Diharapkan seluruh warga dapat berpartisipasi aktif dalam rangkaian kegiatan yang akan berlangsung pada tanggal 17 Agustus mendatang. Hadiah menarik telah disiapkan untuk para pemenang lomba.',
  'https://images.pexels.com/photos/8815238/pexels-photo-8815238.jpeg?auto=compress&cs=tinysrgb&w=600',
  '2024-01-10'
);

-- Insert sample data for anggota
INSERT INTO anggota (nama, jabatan, foto, kontak) VALUES
(
  'Ahmad Syahputra',
  'Anggota',
  'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=300',
  '081234567891'
),
(
  'Dewi Kusuma',
  'Anggota',
  'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=300',
  '081234567892'
),
(
  'Rizki Pratama',
  'Anggota',
  'https://images.pexels.com/photos/1559486/pexels-photo-1559486.jpeg?auto=compress&cs=tinysrgb&w=300',
  '081234567893'
),
(
  'Sari Indah',
  'Anggota',
  'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=300',
  '081234567894'
),
(
  'Bayu Setiawan',
  'Anggota',
  'https://images.pexels.com/photos/1516680/pexels-photo-1516680.jpeg?auto=compress&cs=tinysrgb&w=300',
  '081234567895'
);

-- Insert sample data for galeri
INSERT INTO galeri (url_foto, keterangan) VALUES
(
  'https://images.pexels.com/photos/6646918/pexels-photo-6646918.jpeg?auto=compress&cs=tinysrgb&w=600',
  'Kegiatan Kerja Bakti Bersama Warga'
),
(
  'https://images.pexels.com/photos/8088495/pexels-photo-8088495.jpeg?auto=compress&cs=tinysrgb&w=600',
  'Pengajian Rutin Malam Jumat'
),
(
  'https://images.pexels.com/photos/8815238/pexels-photo-8815238.jpeg?auto=compress&cs=tinysrgb&w=600',
  'Perayaan HUT RI ke-78'
),
(
  'https://images.pexels.com/photos/1181396/pexels-photo-1181396.jpeg?auto=compress&cs=tinysrgb&w=600',
  'Rapat Koordinasi Pengurus'
),
(
  'https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=600',
  'Pelatihan Keterampilan Warga'
),
(
  'https://images.pexels.com/photos/1516680/pexels-photo-1516680.jpeg?auto=compress&cs=tinysrgb&w=600',
  'Kegiatan Sosial untuk Anak Yatim'
);